In [4]:
import numpy as np

In [5]:
a=np.array([1,5,10])
print(a)

[ 1  5 10]


In [6]:
b=np.array([[1,7,20],[5,8,9]])
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [7]:
# dizi boyutunu ogrenmek icin ndim kullanilir
a.ndim

1

In [8]:
b.ndim

2

In [9]:
# iki satir uc sutunlu dizimizin boyunu ogrenmek icin shape kullanilir
b.shape

(2, 3)

In [10]:
a.shape

(3,)

In [11]:
# verilerin tiplerini ogrenmek icin dtype kullanilir
a.dtype

dtype('int64')

In [12]:
# float degerler icerdiginde cikan dtype sonucu asagidaki gibidir
x=np.array([1.0,5.4,10.2])
x.dtype

dtype('float64')

In [13]:
# dizinin belirli bir hucresine erismek icin satir ve sutun bilgisi kullanilir
b[0,2]

20

In [14]:
b[1,1]

8

In [15]:
# burada sadece sifirinci index yani birinci satirin bilgilerini gozlemleyecegiz
b[0]

array([ 1,  7, 20])

In [16]:
# ilk satirdaki ikinci ve ucuncu elemanlara - yani 7 ve 20 degerlerine erismek icin ":" kullaniriz
b[0,1:]

array([ 7, 20])

In [17]:
b[1,1]=18
b[1,1]

18

In [18]:
b

array([[ 1,  7, 20],
       [ 5, 18,  9]])

**Otomatik Dizi Olusturma**

In [19]:
# tumu sifir matrisi
dizi_s = np.zeros((2,3))
dizi_s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# tumu ayni deger olan dizi
dizi1=np.full((4,4),50)
dizi1

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [21]:
# random dizi olusturma
dizi2=np.random.rand(4,3)
dizi2

array([[0.17929073, 0.01796821, 0.39003797],
       [0.86085369, 0.16353592, 0.4071744 ],
       [0.38750639, 0.71208069, 0.14932058],
       [0.07594761, 0.60123158, 0.70341927]])

In [22]:
# otomatik random int dizi olusturma
dizi3=np.random.randint(0,100,size=(5,5))
dizi3

array([[73, 17, 31, 34, 73],
       [57, 44, 14, 40, 29],
       [ 3, 98, 75, 85, 52],
       [99, 77, 64, 31, 73],
       [45, 25, 43, 41, 82]])

**Dizi Kopyalama**

In [23]:
a=np.array([1,2,30])
b=a
b[0]=90
print(a)

[90  2 30]


In [24]:
# bu bir pointer gibi a'nın gosterdigi aynı memory lokasyonunu gosteriyor o nedenle b'deki degisiklik a'da da oluyor.
# bu tarz durumlarla karsilasmamak icin copy() function kullanilmali

a=np.array([1,2,30])
b=a.copy()
b[0]=90
print(a)

[ 1  2 30]


In [25]:
print(b)

[90  2 30]


**Dizilerde Matematiksel Islemler**

In [26]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [27]:
a+4 # her elemana tek tek islem uygulanir

array([5, 6, 7, 8])

In [28]:
a*2

array([2, 4, 6, 8])

In [29]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [30]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [31]:
a**2 # karesi

array([ 1,  4,  9, 16])

**Istatistik**

In [32]:
dizi4=np.array([[1,2,3],[4,5,6]])
dizi4

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.min(dizi4) #dizinin icindeki min deger

1

In [36]:
np.max(dizi4) # dizinin icindeki max deger

6

In [37]:
np.sum(dizi4) # dizi elemanlari toplami

21

**Dosyadan Dizi Yukleme**

In [39]:
filedata=np.genfromtxt('ornek.txt',delimiter=',')
filedata=filedata.astype('int32')
print(filedata)