**Multiple Linear Regression**

In [2]:
# y = a + b1x1 + b2x2 + b3x3 + ...

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
df=pd.read_csv("multilinearregression.csv") # read_csv ile yuklenmis olan csv yi okuttuk
df # gozlemlemek icin print ettik

alan;odasayisi;binayasi;fiyat
0               180;5;10;510000
1               225;4;18;508000
2                260;3;2;548000
3               320;6;10;650000
4                335;4;9;628000
5               345;5;14;632000
6                355;3;0;680000
7               400;4;10;725000

In [5]:
# veri setinde ayirac olarak ";" kullanildigi icin buna gore ayirmak gerekiyor.

df=pd.read_csv("multilinearregression.csv", sep=";") # read_csv ile yuklenmis olan csv yi okuttuk
df # gozlemlemek icin print ettik

alan  odasayisi  binayasi   fiyat
0   180          5        10  510000
1   225          4        18  508000
2   260          3         2  548000
3   320          6        10  650000
4   335          4         9  628000
5   345          5        14  632000
6   355          3         0  680000
7   400          4        10  725000

In [6]:
from sklearn import linear_model

# linear regression modelini tanimlamaliyiz:
reg=linear_model.LinearRegression()

# fit ederken yaptigimiz şey,
# verdigimiz ilk degerlerin independent variable olmasi,
# verdigimiz ikinci degerin dependent variable olmasi.

reg.fit(df[["alan", "odasayisi", "binayasi"]].values, df["fiyat"])


LinearRegression()

In [7]:
df["fiyat"]

0    510000
1    508000
2    548000
3    650000
4    628000
5    632000
6    680000
7    725000
Name: fiyat, dtype: int64

In [8]:
# 230m^2 , 4 odali ve bina yasi 10 olan binanın fiyati?

reg.predict([[230, 4, 10]])

array([530243.29284619])

In [12]:
# 230m^2 , 6 odali ve bina yasi 0 olan binanın fiyati?

reg.predict([[230, 6, 0]])

array([586097.7833456])

In [13]:
# 355m^2 , 3 odali ve bina yasi 20 olan binanın fiyati?

reg.predict([[355, 3, 20]])

array([616657.45791365])

In [14]:
# peki hepsini tek seferde yapabilir miyiz?

reg.predict([[230, 4, 10],[230, 6, 0],[355, 3, 20]])

array([530243.29284619, 586097.7833456 , 616657.45791365])

In [41]:
# coefficient hesaplama, cikan degerler b1,b2 ve b3 olacak.
reg.coef_

array([ 1018.99865454, 14893.82374984, -2606.68429997])

In [42]:
# sabit degeri hesaplama, cikan deger "a" degeri
reg.intercept_

262365.1503032055

In [44]:
a = reg.intercept_
b1 = reg.coef_[0]
b2 = reg.coef_[1]
b3 = reg.coef_[2]

# 230m^2 , 4 odali ve bina yasi 10 olan binanın fiyati formule konularak bulunabilir...

x1 = 230
x2 = 4
x3 = 10

y = a + b1*x1 + b2*x2 + b3*x3

y


530243.2928461881

**Model Save and Load**

In [9]:
import pickle

In [10]:
modelfile="predictingpropertyprice_mlr_model.pickle"

In [11]:
# pickle.dump(model_name,open(model_file,"wb"))
# "wb" open for writing and open in binary mode

pickle.dump(reg,open(modelfile,"wb"))